---
title: "Challenge 2 - Supervised ML - Regeression"
author: "Felix Adamaszek"
---

# Loading the libraries used for different purposes

```{r}

# For standard use
    library(tidyverse)

# For modeling
    library(parsnip)

# For preprocessing & sampling
    library(recipes)
    library(rsample)
    library(workflows)

# For modeling error metrics
    library(yardstick)

# Visualization of decision trees
    library(rpart.plot)

```

# Preparing the needed data

```{r}
    
  bike_orderlines <- read_rds("/Users/felixadamaszek/Documents/GitHub/ss23-bdml-FelixAdams1827/ss23-bdml-FelixAdams1827/content/01_journal/FUNDAMENTAL_DOWNLOADS/bike_orderlines.rds")
    
  neededdata <- bike_orderlines %>% 

#Selecting the needed columns
    
  select(model, model_year, category_1, category_2, category_3, price, frame_material) %>% 

#Removing duplicates and preparing the rows
    
  distinct() %>% 
  na.omit() %>% 
  mutate_if(is.character, as.factor)
  
  glimpse(neededdata)

```

# Splitting the data

```{r}

  set.seed(123)
  
  splitted_data <- initial_split(neededdata, prop = 3/4)
  
  training_data <- training(splitted_data)
  testing_data <- testing(splitted_data)

```

# Using the recipes package

```{r}

  bikes_recipe <- recipe(price ~ ., data = training_data) %>% 

#Adding roles
  update_role(model, new_role = "ID") %>% 
  
#Adding dummy variables
  
  step_dummy(all_nominal(), -all_outcomes()) %>% 
  step_zv(all_predictors())
  
```

# Create Model

```{r}

  lr_mod <-
  linear_reg() %>% 
  set_engine("glm") 

```

# Bundle the model and recipe with workflow package

```{r}

  bikes_workflow <- workflow() %>% 
    add_model(lr_mod) %>% 
    add_recipe(bikes_recipe)
  bikes_workflow

```

# Evaluating the model with the yardstick package 

```{r}

#Fit Model

  bikes_fit <- bikes_workflow %>% 
  fit(data = training_data)

#Prediction

  bikes_prediction <- predict(bikes_fit, testing_data) %>% 
  bind_cols(testing_data %>% select(price, model))

  bikes_prediction %>% 
  metrics(truth = price, estimate = .pred)
  
  ```