---
title: "Automated Machine Learning with H20 (I)"
author: "Felix Adamaszek"
---

# Loading required libraries

```{r}
    library(tidyverse)
    library(GGally)

    employee_attrition_tbl <- read_csv("/Users/felixadamaszek/Documents/GitHub/ss23-bdml-FelixAdams1827/ss23-bdml-FelixAdams1827/content/01_journal/H2O Data/datasets-1067-1925-WA_Fn-UseC_-HR-Employee-Attrition.csv")
  
```

# Interaction between Monthly Income and Attrition?

```{r}

# a. Those that are leaving the company have a higher Monthly Income?
# b. That those are staying have a lower Monthly Income
# c. Those that are leaving have a lower Monthly Income
# d. It's difficult to deduce anything based on the visualization

employee_attrition_tbl %>% 
  select(Attrition, MonthlyIncome) %>% 
  ggpairs(aes(color = Attrition), lower = "blank", legend = 1,
            diag  = list(continuous = wrap("densityDiag", alpha = 0.5))) +
    theme(legend.position = "bottom")
```

Answer c. should be correct

# Interaction between Percent Salary Hike and Attrition?

```{r}

# a. Those that are leaving the company have a higher Percent Salary Hike
# b. Those that are staying have a lower Percent Salary Hike
# c. Those that are leaving have lower Percent Salary Hike
# d. It's difficult to deduce anything based on the visualization

employee_attrition_tbl %>% 
  select(Attrition, PercentSalaryHike) %>% 
  ggpairs(aes(color = Attrition), lower = "blank", legend = 1,
            diag  = list(continuous = wrap("densityDiag", alpha = 0.5))) +
    theme(legend.position = "bottom")
```

Answer d. should be correct
