project:
  type: website
  # output-dir: docs
execute: 
  freeze: auto  # Re-render only when source changes
  cache: true

website:
  title: "MyLabJournal"
  favicon: assets/icons/favicon.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Journal"
        menu: 
          - text: "Challenge 1"
            file: content/01_journal/challenge_1.qmd
          - text: "Challenge 2"
            file: content/01_journal/Challenge_2.qmd
          - text: "Challenge 3"
            file: content/01_journal/Challenge_3.qmd
          - text: "Challenge 4"
            file: content/01_journal/Challenge_4.qmd
          - text: "Challenge 5"
            file: content/01_journal/Challenge_5.qmd
          - text: "Challenge 6"
            file: content/01_journal/Challenge_6.qmd
      - text: "Class notes"
        file: content/02_notes/05_class_notes.qmd
      - text: "Links"
        file: content/03_other/06_links.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    highlight-style: a11y-dark
filters:
   - lightbox
lightbox: auto